name: arcgis_overture

channels:
  - esri
  - conda-forge

dependencies:
  - appnope
  - arcgis
  - arcgis-mapping
  - black>=21
  - jupyterlab
  - jupyterlab_code_formatter
  - nodejs
  - pip
  - pytest
  - pyarrow
  - pyyaml
  - tqdm
  - pip:
    - azure-storage-blob
    - boto3
    - build
    - bump2version
    - mkdocs
    - mkdocs-glightbox
    - mkdocs-include-markdown-plugin
    - mkdocs-jupyter
    - mkdocs-material
    - mkdocstrings[python]>=0.18
    - overturemaps
    - twine
